baseurl = "https://zyuce.github.io/personal_site/"
languageCode = "en-us"
Title = "Liang Ce"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

# Google Analytics API key.
googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  custom_css = ["/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  # Disqus shortname
  disqus = ""
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "学习笔记"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"


[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
